In [2]:
import numpy as np


X_train = np.array([[1,2,3],[1,2,3]])
X_test = np.array([[1,2,1],[1,2,3]])
test = np.repeat(X_test, X_train.shape[0], axis=0)
train = np.tile(X_train, (X_test.shape[0], 1))

delta = test-train
L1 = np.sum(np.abs(delta), axis=1, keepdims=True)
L1 = L1.reshape(X_test.shape[0] ,X_train.shape[0])
print(L1)

L2 = np.sqrt(np.sum(delta**2, axis=1, keepdims=True)) #complete
L2 = L2.reshape(X_test.shape[0] ,X_train.shape[0])
print(L2)

L3 = np.max(np.abs(delta), axis=1, keepdims=True) #complete
L3 = L3.reshape(X_test.shape[0] ,X_train.shape[0])
print(L3)

[[2 2]
 [0 0]]
[[2. 2.]
 [0. 0.]]
[[2 2]
 [0 0]]


In [3]:
import numpy as np

# 原始矩阵
matrix = np.array([[1, 2, 0, 0, 4],
                  [2, 21, 2, 3, 3]])

# 找到每行中最小的n个数的索引
n = 2
min_indices = np.argpartition(matrix, n, axis=1)[:, :n]
min_indices = np.sort(min_indices, axis=1)

# 打印最小值的索引矩阵
print(min_indices)


[[2 3]
 [0 2]]


In [4]:
import numpy as np

# 原始矩阵
matrix = np.array([[1, 2, 0, 3, 4],
                  [112, 21, 2, 3, 3]])

# 对每行进行从小到大的排序
sorted_matrix = np.sort(matrix, axis=1)

# 打印排序后的矩阵
print(sorted_matrix)


[[  0   1   2   3   4]
 [  2   3   3  21 112]]


In [5]:
import numpy as np

# 原始数据
data = np.array([0, 3, 5, 7, 9])

# 索引矩阵
indices = np.array([[0, 1], [1, 3], [1, 4]])

# 使用索引矩阵获取对应的数值
result = data[indices]

# 打印结果矩阵
print(result)
print(data.shape)

[[0 3]
 [3 7]
 [3 9]]
(5,)


In [6]:
import numpy as np

# Create the input matrix (replace this with your data)
input_matrix = np.array([[0, 1, 0, 1, 1],
                         [1, 1, 0, 0, 1],
                         [0, 0, 1, 1, 0]])

# Count the occurrences of 0 and 1 in each row
count_0 = np.sum(input_matrix == 0, axis=1)
count_1 = np.sum(input_matrix == 1, axis=1)

# Construct a new matrix with the counts
count_matrix = np.column_stack((count_0, count_1))

print("Input Matrix:")
print(input_matrix)
print("Count Matrix:")
print(count_matrix)


Input Matrix:
[[0 1 0 1 1]
 [1 1 0 0 1]
 [0 0 1 1 0]]
Count Matrix:
[[2 3]
 [2 3]
 [3 2]]


In [7]:
import numpy as np

# 创建一个示例数组
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 使用切片操作获取第一列
first_column = arr[:, 0]

# 输出第一列
print(first_column)


[1 4 7]


In [8]:
import numpy as np

# traning samples
with open("testcase_0/0.in", "r") as file:
    num_training_samples = int(file.readline().strip())
    training_samples = []
    for _ in range(num_training_samples):
        line = file.readline().strip().split()
        label = int(line[0])
        features = [float(x) for x in line[1:]]
        training_samples.append([label] + features)

training_samples = np.array(training_samples)
training_labels = training_samples[:, 0]
training_features = training_samples[:, 1:]

# testing samples
with open("testcase_0/0.in", "r") as file:
    for _ in range(num_training_samples + 1):
        file.readline()

    num_testing_samples = int(file.readline().strip())
    testing_samples = []
    for _ in range(num_testing_samples):
        line = file.readline().strip().split()
        label = int(line[0])
        features = [float(x) for x in line[1:]]
        testing_samples.append([label] + features)

testing_samples = np.array(testing_samples)
testing_labels = testing_samples[:, 0]
testing_features = testing_samples[:, 1:]










print(training_samples.shape)
print(testing_samples.shape)
print(num_training_samples)
print(num_testing_samples)

print(testing_labels.shape)
print(training_labels.shape)

print(testing_features.shape)
print(training_features.shape)

(455, 31)
(114, 31)
455
114
(114,)
(455,)
(114, 30)
(455, 30)


In [9]:
import numpy as np

# 创建示例数组
arr = testing_samples

# 使用numpy.argsort函数获取新的行索引
new_order = np.argsort(arr[:, 0])

# 使用新的行索引重新排列数组
rearranged_arr = arr[new_order]

# 输出重新排列后的数组
print("重新排列后的数组:")
print(rearranged_arr)

# 使用逆排序恢复原始顺序
restored_order = np.argsort(new_order)
restored_arr = rearranged_arr[restored_order]

# 输出恢复后的数组
print("恢复后的数组:")
print(restored_arr)


重新排列后的数组:
[[ 3.      10.71    20.39    ...  0.086    0.2605   0.08701]
 [ 3.      16.27    20.71    ...  0.1583   0.3103   0.082  ]
 [ 3.      19.21    18.57    ...  0.2091   0.3537   0.08294]
 ...
 [ 7.      12.25    22.44    ...  0.06335  0.31     0.08203]
 [ 7.      12.65    18.17    ...  0.1407   0.323    0.1033 ]
 [ 7.      10.97    17.2     ...  0.1555   0.254    0.09532]]
恢复后的数组:
[[ 3.      10.71    20.39    ...  0.086    0.2605   0.08701]
 [ 3.      15.61    19.38    ...  0.08568  0.2683   0.06829]
 [ 5.      18.63    25.11    ...  0.1848   0.3444   0.09782]
 ...
 [ 7.      12.06    18.9     ...  0.05093  0.288    0.08083]
 [ 7.      13.73    22.61    ...  0.2208   0.3596   0.1431 ]
 [ 5.       9.777   16.99    ...  0.05334  0.2533   0.08468]]


In [10]:
import numpy as np

# 创建示例数组
arr = np.array([[3, 1, 1, 1],
                [7, 1, 1, 1],
                [3, 2, 1, 1],
                [5, 1, 1, 4]])

# 使用numpy.argsort函数获取新的行索引
new_order = np.argsort(arr[:, 0])

# 创建一个示例向量（这里用简单的示例向量代替计算得到的向量）
# 在实际情况下，这个向量应该是通过某种计算得到的
computed_vector = np.array([10, 20, 30, 40])

# 使用新的行索引将向量重新排列
rearranged_vector = computed_vector[new_order]

# 输出重新排列后的向量
print("重新排列后的向量:")
print(rearranged_vector)

# 使用逆排序（原始排序的逆序）将向量还原到原始顺序
restored_order = np.argsort(new_order)
restored_vector = rearranged_vector[restored_order]

# 输出恢复后的向量
print("恢复后的向量:")
print(restored_vector)


重新排列后的向量:
[10 30 40 20]
恢复后的向量:
[10 20 30 40]


In [11]:
import numpy as np

# 创建示例数组
arr = np.array([[3, 1, 1, 1],
                [3, 1, 2, 1],
                [5, 1, 3, 1],
                [7, 1, 3, 1],
                [7, 1, 3, 1]])

# 获取第一列的唯一值和对应的索引
unique_values, indices = np.unique(arr[:, 0], return_inverse=True)

# 使用np.split按唯一值的索引分割成多个矩阵
matrices = np.split(arr, np.where(indices[1:] != indices[:-1])[0] + 1)

# 输出分割后的矩阵
for i, matrix in enumerate(matrices):
    print(f"Matrix {i + 1}:\n{matrix}")


Matrix 1:
[[3 1 1 1]
 [3 1 2 1]]
Matrix 2:
[[5 1 3 1]]
Matrix 3:
[[7 1 3 1]
 [7 1 3 1]]


In [12]:
import numpy as np

# 创建两个示例数组
array1 = np.array([[1], [0]])
array2 = np.array([[1]])

# 使用np.concatenate函数将它们拼接
result = np.concatenate((array1, array2))

# 打印拼接后的结果
print(result)


[[1]
 [0]
 [1]]


In [1]:
import numpy as np

array1 = np.array([[1], [1], [1]])
array2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

result = np.hstack((array1, array2))
print(result)


[[1 1 2 3]
 [1 1 2 3]
 [1 1 2 3]]


In [2]:
import numpy as np

# 创建一个示例数组
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 对行进行相加
row_sums = np.sum(array, axis=0)

# 打印结果
print("Row Sums:")
print(row_sums)


Row Sums:
[12 15 18]


In [3]:
import numpy as np

# 创建两个矩阵
matrix_a = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix_b = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# 使用 numpy.dot() 函数进行矩阵乘法
result = np.dot(matrix_a, matrix_b)

# 或者使用 @ 运算符
# result = matrix_a @ matrix_b

# 打印结果
print("Result of Matrix Multiplication:")
print(result)


Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


In [4]:
import numpy as np

# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

# 使用矩阵的 .T 属性进行转置
transposed_matrix = matrix.T

# 打印结果
print("Transposed Matrix:")
print(transposed_matrix)


Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np

# 创建两个数组
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# 使用 * 运算符进行元素对应相乘
result = array_a * array_b

# 打印结果
print("Element-Wise Multiplication Result:")
print(result)


Element-Wise Multiplication Result:
[ 4 10 18]


In [8]:
import numpy as np

# 创建两个列表
list1 = [[1, 1, 1]]
list2 = [[1, 1, 1]]

# 使用 numpy.vstack() 函数进行行拼接
result = np.vstack([list1, list2])

# 打印结果
print(result)


[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np

# 三个类别的均值向量
mu_1 = ...  # 类别1的均值向量
mu_2 = ...  # 类别2的均值向量
mu_3 = ...  # 类别3的均值向量

# 全局均值向量
mu = (N1 * mu_1 + N2 * mu_2 + N3 * mu_3) / (N1 + N2 + N3)

# 计算SB矩阵
SB = N1 * np.outer(mu_1 - mu, mu_1 - mu) + N2 * np.outer(mu_2 - mu, mu_2 - mu) + N3 * np.outer(mu_3 - mu, mu_3 - mu)


In [2]:
import numpy as np

num_class_i = np.array([0])
matrix = np.array([[1, 2], [3, 4]])  # 这里假设 matrix 是一个示例矩阵

# 使用 np.concatenate 拼接数组
result = np.concatenate(num_class_i, np.array([matrix.shape[0]]))

print(result)


TypeError: only integer scalar arrays can be converted to a scalar index

In [3]:
import numpy as np

# 创建一个示例矩阵，假设有n列
n = 3
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 初始化一个用于存储结果的矩阵
result_matrix = np.zeros((n, n))

# 逐列计算矩阵的列向量与其自身转置的乘积，然后相加
for i in range(n):
    column_vector = matrix[:, i]  # 获取第i列
    column_matrix = np.outer(column_vector, column_vector)  # 列向量与其自身的转置
    result_matrix += column_matrix

print("Resulting Matrix:")
print(result_matrix)


Resulting Matrix:
[[ 14.  32.  50.]
 [ 32.  77. 122.]
 [ 50. 122. 194.]]


In [4]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[1, 2,3],
                  [2,2, 1]])

# 找到每行中的最大值及其索引
# max_values = np.max(matrix, axis=1)  # 找到每行中的最大值
max_indices = np.argmax(matrix, axis=1)  # 找到每行中最大值的索引

# 创建一个新的矩阵，包含每行中的最大值的索引
result = max_indices

# 打印结果
print(result)


[2 0]


In [16]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[0.1, 0.9, 0, 0],
                  [2, 2, 2, 2]])

# 计算加权平均值
weights = np.array([0, 1, 2, 3])  # 权重数组
result = np.sum(matrix * weights, axis=1) / np.sum(matrix, axis=1)
result = np.round(result)
# 打印结果
print(result)


[1. 2.]


In [13]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[0.2, 0, 0, 0.9],
                  [2, 4, 1, 8],
                  [3, 6, 9, 12]])

# 计算每行的结果并取最接近的整数
row_results = np.sum(matrix * np.arange(matrix.shape[1]), axis=1) / np.sum(matrix, axis=1)
rounded_results = np.round(row_results).astype(int)

# 打印结果
print(rounded_results)


[2 2 2]


In [17]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[0.6, 1.4],
                  [2.0, 3.0]])

# 计算每行的和
row_sums = np.sum(matrix, axis=1)

# 将每个元素除以其对应行的和
normalized_matrix = matrix / row_sums[:, np.newaxis]

# 打印结果
print(normalized_matrix)


[[0.3 0.7]
 [0.4 0.6]]
